CityList = new Object();
CityList["HA"]=new Object();
CityList["HA"]["802"]="マウイ島";
CityList["HA"]["803"]="ハワイ島";
CityList["HA"]["804"]="オアフ島";
CityList["HA"]["HNL"]="ホノルル";
CityList["HA"]["ITO"]="ヒロ";
CityList["HA"]["KOA"]="カイルア コナ";
CityList["HA"]["OGG"]="カフルイ";
